hikingapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from hikingapp import settings
from trip.views import handler_403, handler_404, handler_500

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    # path('category/', include('categories.urls', namespace='cat')),
    # path('image/', include('images.urls', namespace='image')),
    # path('tag/', include('tags.urls', namespace='tag')),
    # path('users/', include('users.urls', namespace='users')),
    # path('social/', include('social_django.urls', namespace='social')),
]
urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    path('category/', include('categories.urls', namespace='cat')),
    path('image/', include('images.urls', namespace='image')),
    path('tag/', include('tags.urls', namespace='tag')),
    path('users/', include('users.urls', namespace='users')),
    path('social/', include('social_django.urls', namespace='social')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

handler404 = handler_404
handler403 = handler_403
handler500 = handler_500

tags/urls.py
from django.urls import path

from tags.views import TripTag, ShowAllTags, AddTag

app_name = 'tag'

urlpatterns = [
    path('', ShowAllTags.as_view(), name='all_tags'),
    path('add/', AddTag.as_view(), name='add_tag'),
    path('<slug:slug>/', TripTag.as_view(), name='tag'),
]

tags/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Tag(models.Model):
    tag = models.CharField(max_length=40, db_index=True)
    slug = models.SlugField(max_length=40, db_index=True, unique=True)

    class Meta:
        db_table = 'tags'
        ordering = ['-id']

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('tag:tag', kwargs={'slug': self.slug})

tags/forms.py
from django import forms

from tags.models import Tag


class AddTagForm(forms.ModelForm):
    # tag = forms.CharField(max_length=40)

    class Meta:
        model = Tag
        fields = [
            'tag',
            # 'slug',
        ]

tags/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from tags.forms import AddTagForm
from tags.models import Tag

from trip.models import Trip
from trip.utils import generate_unique_slug, DataMixin


# Create your views here.

class ShowAllTags(ListView):
    template_name = 'tags/show_all_tags.html'
    context_object_name = 'tags'

    def get_queryset(self):
        return Tag.objects.all()


class TripTag(DataMixin, ListView):
    template_name = 'trip/index.html'
    context_object_name = 'trips'

    def get_queryset(self):
        return (Trip.objects.filter(tag__slug=self.kwargs['slug'], published=True).
                select_related('category').
                prefetch_related('user', 'tag'))


class AddTag(LoginRequiredMixin, CreateView):
    form_class = AddTagForm
    template_name = 'tags/add_tag.html'
    success_url = reverse_lazy('tag:all_tags')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        f = form.save()
        tag = form.cleaned_data['tag']
        f.slug = generate_unique_slug(Tag, tag)

        return super().form_valid(form)

tags/templates/tags/add_tag.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Add tag' %}</h4>
             <p> </p>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                            <p><label class="form">{{ f.tag }}</label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}
                    <p><button type="submit" class="btn btn-success">{% translate 'Submit' %}</button> </p>
                </form>
             <p> </p>
         </div>
    </div>
</div>

{% endblock %}

tags/templates/tags/show_all_tags.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Tags' %}</h4>
             <p> </p>
                 <form action="{% url 'tag:add_tag' %}" method="get">
                     <button type="submit" class="btn btn-success">{% translate 'Add tag' %}</button>
                 </form>
             <p> </p>
                {% for t in tags %}
                <form action="{{t.get_absolute_url}}" method="get">
                    <p><button type="submit" class="btn btn-outline-dark">{{ t.tag }}</button></p>
                </form>
             <p> </p>
                {% endfor %}
         </div>
    </div>
</div>

{% endblock %}

tags/templates/tags/show_tag.html
<!--{% extends 'base.html' %}-->

<!--{% block content %}-->


<!--{% for t in trips %}-->

<!--    <p>Name: {{t.title}}</p>-->
<!--    <p>Slug: {{t.slug}}</p>-->
<!--    <p>CATEgORY: {{t.category}}</p>-->
<!--    <p>Content: {{t.content}}</p>-->
<!--    {% for i in t.tag.all %}-->
<!--        <a class ="link-read-post" href="{{ i.get_absolute_url }}">{{ i.tag }}</a>-->
<!--    {% endfor %}-->

<!--    {% if t.title_photo %}-->
<!--            <p><img src="{{ t.title_photo.url }}" class="img" width="480" height="330"></p>-->
<!--    {% endif %}-->
<!--{% endfor %}-->

<!--{% endblock %}-->

<!--{% block navigation %}-->
<!--{% if page_obj.has_other_pages %}-->
<!--<nav class="list-pages">-->
<!--    <ul>-->
<!--		{% if page_obj.has_previous %}-->
<!--		<li class="page-num">-->
<!--			<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>-->
<!--		</li>-->
<!--		{% endif %}-->

<!--        {% for p in paginator.page_range %}-->
<!--		{% if page_obj.number == p %}-->
<!--		<li class="page-num page-num-selected">{{ p }}</li>-->
<!--		{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}-->
<!--        <li class="page-num">-->
<!--            <a href="?page={{ p }}">{{ p }}</a>-->
<!--        </li>-->
<!--		{% endif %}-->
<!--        {% endfor %}-->

<!--		{% if page_obj.has_next %}-->
<!--		<li class="page-num">-->
<!--			<a href="?page={{ page_obj.next_page_number }}">&gt;</a>-->
<!--		</li>-->
<!--		{% endif %}-->

<!--    </ul>-->
<!--</nav>-->
<!--{% endif %}-->
<!--{% endblock %}-->