hikingapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from hikingapp import settings
from trip.views import handler_403, handler_404, handler_500

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    # path('category/', include('categories.urls', namespace='cat')),
    # path('image/', include('images.urls', namespace='image')),
    # path('tag/', include('tags.urls', namespace='tag')),
    # path('users/', include('users.urls', namespace='users')),
    # path('social/', include('social_django.urls', namespace='social')),
]
urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    path('category/', include('categories.urls', namespace='cat')),
    path('image/', include('images.urls', namespace='image')),
    path('tag/', include('tags.urls', namespace='tag')),
    path('users/', include('users.urls', namespace='users')),
    path('social/', include('social_django.urls', namespace='social')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

handler404 = handler_404
handler403 = handler_403
handler500 = handler_500

tags/urls.py
from django.urls import path

from tags.views import TripTag, ShowAllTags, AddTag

app_name = 'tag'

urlpatterns = [
    path('', ShowAllTags.as_view(), name='all_tags'),
    path('add/', AddTag.as_view(), name='add_tag'),
    path('<slug:slug>/', TripTag.as_view(), name='tag'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.views import ProfileUser, LoginUser, RegisterUser, PasswordChangeUser, PasswordChangeDoneUser, UserTrips

app_name = 'users'

urlpatterns = [
    path('trip/<str:username>', UserTrips.as_view(), name='user_trips'),

    path('profile/', ProfileUser.as_view(), name='profile'),
    path('register/', RegisterUser.as_view(), name='register'),

    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password_change/', PasswordChangeUser.as_view(),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneUser.as_view(),
         name='password_change_done'),

    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset.html',
             email_template_name='users/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    path('password_reset_done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password_reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password_reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField
from django.utils.translation import gettext_lazy as _


# Create your models here.
class User(AbstractUser):
    UNDECIDED = 'U'
    MALE = 'M'
    FEMALE = 'F'
    ATTACK_HELICOPTER = 'H'
    GENDER_LIST = {
        'U': _('Undecided'),
        'M': _('Male'),
        'F': _('Female'),
        'H': _('Attack Helicopter'),
    }

    avatar = ThumbnailerImageField(upload_to='users/%Y/%m/%d/', blank=True, null=True, verbose_name=_('avatar'))
    birthday = models.DateTimeField(blank=True, null=True, verbose_name=_('birthday'))
    gender = models.CharField(_('gender'), max_length=3, choices=GENDER_LIST, default=UNDECIDED)

users/forms.py
import datetime
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.utils.translation import gettext_lazy as _


class ProfileUserForm(forms.ModelForm):
    year = datetime.date.today().year
    birthday = forms.DateTimeField(label=_('birthday'),
                                   widget=forms.SelectDateWidget(years=tuple(range(year - 100, year - 5))))

    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'birthday',
            'gender',
            'avatar',

        ]


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = [
            _('username'),
            _('password'),
        ]


class RegisterUserForm(UserCreationForm):
    password1 = forms.CharField(label=_('Password'), widget=forms.PasswordInput())
    password2 = forms.CharField(label=_('Repeat password'), widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('This email already used')
        return email


class PasswordChangeUserForm(PasswordChangeForm):
    old_password = forms.CharField(label=_('Old password'),
                                   widget=forms.PasswordInput())
    new_password1 = forms.CharField(label=_('New password'),
                                    widget=forms.PasswordInput())
    new_password2 = forms.CharField(label=_('Repeat new password'),
                                    widget=forms.PasswordInput())

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, ListView

from trip.models import Trip
from trip.utils import DataMixin
from users.forms import ProfileUserForm, LoginUserForm, RegisterUserForm, PasswordChangeUserForm


class UserTrips(DataMixin, ListView):
    template_name = 'trip/index.html'
    context_object_name = 'trips'

    def get_queryset(self):
        return (Trip.objects.filter(user__username=self.kwargs['username']).
                select_related('category').
                prefetch_related('user', 'tag'))


class ProfileUser(UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    context_object_name = 'user'

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'

    # def get_success_url(self):
    #     return reverse_lazy('home')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class PasswordChangeUser(PasswordChangeView):
    form_class = PasswordChangeUserForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change.html'


class PasswordChangeDoneUser(PasswordChangeDoneView):
    template_name = 'users/password_change_done.html'

users/templates/users/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}


<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Authorization' %}</h4>
             <p> </p>
                <form method="post">
                    <input type="hidden" name="next" value="{{ next }}" />
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label">{{ f.label }}</label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <p><a href="{% url 'users:password_reset' %}"
                          class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                        {% translate 'Forgot your password?' %}</a></p>
                    <p><button type="submit" class="btn btn-success">{% translate 'Enter' %}</button></p>
                </form>
             <p> </p>
         </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
<!--            <p><a href='{% url "social:begin" "vk-oauth2" %}'>Sign in with VK</a></p>-->
<!--            <p><a href='{% url "social:begin" "google-oauth2" %}'>Sign in with Google</a></p>-->
            <p><a href='{% url "social:begin" "github" %}'
                  class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                {% translate 'Sign in with GitHub' %}</a></p>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_change.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Change password' %}</h4>
             <p> </p>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label">{{ f.label }}</label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}

                    <p><button type="submit" class="btn btn-success">{% translate 'Change password' %}</button> </p>
                </form>
             <p> </p>
         </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Password successfully changed' %}</h4>
             <p> </p>
                <p>{% blocktranslate %}You have successfully changed your password.{% endblocktranslate %}
                    <a href="{% url 'users:profile' %}">{% translate 'Go to Profile.' %}</a></p>
             <p> </p>
         </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Reset password' %}</h4>
             <p> </p>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                        <p><label class="form-label">{{ f.label }}</label>{{ f }}</p>
                        <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <p><button type="submit" class="btn btn-success">{% translate 'Reset to E-mail' %}</button> </p>
                </form>
             <p> </p>
         </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Password successfully changed' %}</h4>
             <p> </p>
                <p>{% blocktranslate %}Reset password change is successful. Use new password for {% endblocktranslate %}
                    <a href="{% url 'users:login' %}">{% translate 'enter in a system.' %}</a> </p>
             <p> </p>
         </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'New password' %}</h4>
             <p> </p>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label">{{ f.label }}</label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <p><button type="submit" class="btn btn-success">{% translate 'Save' %}</button> </p>
                </form>
             <p> </p>
         </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Reset password' %}</h4>
             <p> </p>
                <p>{% blocktranslate %}We’ve emailed you instructions for setting your password,
                    if an account exists with the email you entered.
                    You should receive them shortly.{% endblocktranslate %} </p>
                <p>{% blocktranslate %}If you don’t receive an email,
                    please make sure you’ve entered the address you registered with,
                    and check your spam folder.{% endblocktranslate %}</p>
             <p> </p>
         </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% load thumbnail %}

<div class="container">
    <div class="row">
         <div class="col">
             <div class="row">
                <p><img src="{{ user.avatar|thumbnail_url:'icon' }}"> {{user.username}}</p>
             </div>

            <p> </p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for f in form %}
                    <p><label class="form-label" >{{ f.label }}</label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                 <div class="row">
                    <p><button type="submit" class="btn btn-success">{% translate 'Save' %}</button> </p>
                 </div>
            </form>
             <p> </p>

            <p><a href="{% url 'users:password_change' %}"
                  class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                {% translate 'Change password' %}</a></p>
         </div>
         <div class="col">
             {% if user.avatar %}
                <p><img src="{{ user.avatar|thumbnail_url:'avatar' }}" alt=""></p>
             {% else %}
                 <p><img src="/media/users/default.jpg"></p>
             {% endif %}
         </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
         <div class="col">
             <h4>{% translate 'Registration' %}</h4>
             <p> </p>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}" />
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <p><label class="form-label">{{ f.label }}</label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endfor %}
                    <p><button type="submit" class="btn btn-success">{% translate 'Registration' %}</button> </p>
                </form>
             <p> </p>
         </div>
    </div>
</div>

{% endblock %}