categories/urls.py
from django.urls import path

from categories.views import TripCategory, ShowAllCategories

app_name = 'cat'

urlpatterns = [

    path('<slug:slug>/', TripCategory.as_view(), name='categories'),
    path('', ShowAllCategories.as_view(), name='all_categories'),

]

hikingapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from hikingapp import settings
from trip.views import handler_403, handler_404, handler_500

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    # path('category/', include('categories.urls', namespace='cat')),
    # path('image/', include('images.urls', namespace='image')),
    # path('tag/', include('tags.urls', namespace='tag')),
    # path('users/', include('users.urls', namespace='users')),
    # path('social/', include('social_django.urls', namespace='social')),
]
urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    path('category/', include('categories.urls', namespace='cat')),
    path('image/', include('images.urls', namespace='image')),
    path('tag/', include('tags.urls', namespace='tag')),
    path('users/', include('users.urls', namespace='users')),
    path('social/', include('social_django.urls', namespace='social')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

handler404 = handler_404
handler403 = handler_403
handler500 = handler_500

images/urls.py
from django.urls import path

from images.views import ShowGallery

app_name = 'image'

urlpatterns = [
    path('gallery/', ShowGallery.as_view(), name='gallery'),
]

tags/urls.py
from django.urls import path

from tags.views import TripTag, ShowAllTags, AddTag

app_name = 'tag'

urlpatterns = [
    path('', ShowAllTags.as_view(), name='all_tags'),
    path('add/', AddTag.as_view(), name='add_tag'),
    path('<slug:slug>/', TripTag.as_view(), name='tag'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.views import ProfileUser, LoginUser, RegisterUser, PasswordChangeUser, PasswordChangeDoneUser, UserTrips

app_name = 'users'

urlpatterns = [
    path('trip/<str:username>', UserTrips.as_view(), name='user_trips'),

    path('profile/', ProfileUser.as_view(), name='profile'),
    path('register/', RegisterUser.as_view(), name='register'),

    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password_change/', PasswordChangeUser.as_view(),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneUser.as_view(),
         name='password_change_done'),

    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset.html',
             email_template_name='users/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    path('password_reset_done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password_reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password_reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

]

templates/base.html
<!doctype html>
{% load i18n %}
{% load static %}
{% load thumbnail %}

<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hikingapp</title>
    <link type="text/css" href="{% static 'trip/css/styles.css' %}" rel="stylesheet" />
    <link rel="shortcut icon" href="{% static 'trip/images/favicon.ico' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet">

  </head>

<body>
    <style>
      body {
        background: #c4de97
      }
    </style>

 <header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'home' %}" class="nav-link px-2 link-body-emphasis">Hikingapp</a></li>
        <li><a href="{% url 'add' %}" class="nav-link px-2 link-body-emphasis">{% translate 'New trip' %}</a></li>

        <li class="dropdown text-end">
          <a href="#" class="nav-link px-2 link-body-emphasis text-decoration-none dropdown-toggle"
              data-bs-toggle="dropdown" aria-expanded="false">{% translate 'Order by' %}</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'tag:all_tags' %}">{% translate 'Tags' %}</a></li>
            <li><a class="dropdown-item" href="{% url 'cat:all_categories' %}">{% translate 'Categories' %}</a></li>
          </ul>
        </li>
        <li><a href="{% url 'image:gallery' %}" class="nav-link px-2 link-body-emphasis">{% translate 'Gallery' %}</a></li>
        <li><a href="{% url 'about' %}" class="nav-link px-2 link-body-emphasis">{% translate 'About' %}</a></li>

      </ul>

          <div class="dropdown text-end">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
                <a href="#" class="nav-link px-2 link-body-emphasis text-decoration-none dropdown-toggle"
                      data-bs-toggle="dropdown" aria-expanded="false">{{ LANGUAGE_CODE }}</a>
        <ul class="dropdown-menu">
            {% for language in languages %}
          <li>
            <a class="dropdown-item" href="/{{ language.code }}/"
                 {% if language.code == LANGUAGE_CODE %} class="selected" {% endif %}>
                      {{ language.name_local }}</a>
            {% endfor %}
          </li>
        </ul>
    </div>

      <form action="{% url 'search' %}" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" method="get">
          <input class="form-control" type="search" name="search" placeholder={% translate 'search trip...' %}  aria-label="Search">
      </form>

      {% if user.is_authenticated %}

      <div class="dropdown text-end">
        <a href="{% url 'users:profile' %}" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
          data-bs-toggle="dropdown" aria-expanded="false">{{user.username}}</a>
      <ul class="dropdown-menu text-small">
        <li><a class="dropdown-item" href="{% url 'add' %}">{% translate 'New trip' %}</a></li>
        <li><a class="dropdown-item" href="{% url 'users:user_trips' user.username %}">{% translate 'My trips' %}</a></li>
        <li><a class="dropdown-item" href="{% url 'users:profile' %}">{% translate 'Profile' %}</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item">
            <form action="{% url 'users:logout' %}" method="post">
                  {% csrf_token %}
              <button type="submit" class="btn btn-success">{% translate 'Exit' %}</button>
            </form>
            </a>
        </li>
      </ul>
      </div>

      {% else %}
            <li class="nav-link active"><a href="{% url 'users:login' %}" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">{% translate 'Login' %}</a> |
                <a href="{% url 'users:register' %}" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">{% translate 'Registration' %}</a> </li>
            <li class="nav-link active"></li>
      {% endif %}
    </div>
  </div>
 </header>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>



<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
  {% block content %}
  {% endblock %}
	</div>
<!-- Конец блока контента -->

<!-- Блок навигации -->
  {% block navigation %}
  {% endblock %}
<!-- Конец блока навигации -->
<!-- Footer -->
  <div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="col-md-4 d-flex align-items-center">Hikingapp.ru | E-mail: info@hikingapp.ru</div>
      <div class="nav-link active">
        <a href ="{% url 'terms' %}"
           class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
          {% translate 'Terms of use' %}</a>
      </div>
    </footer>
  </div>
<!-- Конец footer'а и страницы -->
</body>
</html>